# Site settings
title: Chethan R
description: CV Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Chethan R
user_description: Resume.
user_title: A Student at DSU.
email: chethanrraj90@gmail.com
# twitter_username: lorem_ipsum
# github_username:  chethanrraj90
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
